### ISSUE TITLE
Initialize from a state file

### ISSUE THREAD

**Issue by zhangchicool** [zhangchicool/speciesnetwork#1]
TODO

**Comment by Anaphory** [comment]
Assuming you mean the kind of thing that happens when running `beast -resume`, then currently this is what happens:

```
java.lang.NullPointerException
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:129)
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:150)
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
        at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
        at speciesnetwork.GeneTreeInSpeciesNetwork.update(GeneTreeInSpeciesNetwork.java:117)
        at speciesnetwork.GeneTreeInSpeciesNetwork.computeCoalescentTimes(GeneTreeInSpeciesNetwork.java:96)
        at speciesnetwork.MultispeciesCoalescent.calculateLogP(MultispeciesCoalescent.java:90)
        at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
        at beast.core.MCMC.propagateState(Unknown Source)
        at beast.core.MCMC.doLoop(Unknown Source)
        at beast.core.MCMC.run(Unknown Source)
        at beast.app.BeastMCMC.run(Unknown Source)
        at beast.app.beastapp.BeastMain.<init>(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
```

Given my bad track record with trying to modify `GeneTreeInSpeciesNetwork`, I don't dare to try and fix this, but it would be awesome if it could be done.

**Comment by Anaphory** [comment]
Miraculously, it still does *something*. I can't say how reliable that is, and the number of `NullPointerException`s between two log outputs does not seem to decrease.
