### ISSUE TITLE
nextSpeciesBranchNumber < 0

### ISSUE THREAD

**Issue by Anaphory** [zhangchicool/speciesnetwork#4]
After wondering why I get so many NullPointerExceptions, 
```
	at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
	at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
	at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
	at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
	at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
	at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:158)
	at speciesnetwork.GeneTreeInSpeciesNetwork.update(GeneTreeInSpeciesNetwork.java:117)
	at speciesnetwork.GeneTreeInSpeciesNetwork.computeCoalescentTimes(GeneTreeInSpeciesNetwork.java:96)
	at speciesnetwork.MultispeciesCoalescent.calculateLogP(MultispeciesCoalescent.java:90)
	at beast.core.util.CompoundDistribution.calculateLogP(CompoundDistribution.java:114)
	at beast.core.MCMC.propagateState(MCMC.java:496)
	at beast.core.MCMC.doLoop(MCMC.java:383)
	at beast.core.MCMC.run(MCMC.java:353)
	at beast.app.BeastMCMC.run(BeastMCMC.java:357)
	at beast.app.beastapp.BeastMain.<init>(BeastMain.java:113)
	at beast.app.beastapp.BeastMain.main(BeastMain.java:659)
```

I noticed the assertions in
https://github.com/zhangchicool/speciesnetwork/blob/d26c5289d9d8ad5b09f5c7c2ac9a8f45bdab3491/src/speciesnetwork/GeneTreeInSpeciesNetwork.java#L147
and below and activated assertions in the JVM, which led to `Exception in thread "main" java.lang.AssertionError 	at speciesnetwork.GeneTreeInSpeciesNetwork.recurseCoalescentEvents(GeneTreeInSpeciesNetwork.java:147)`.

I don't know how traversal numbers should behave and what the getDirection function is supposed to do,

            final int traversalNodeNumber = speciesNetworkNode.getTraversalNumber();
            final Integer nextSpeciesBranchNumber = geneTree.embedding.getDirection(geneTreeNodeNumber, traversalNodeNumber);

but the calls above that look reasonable.
@zhangchicool I sent you my XML files that produce this issue, in case that might help track down the problem because it's a user error.

**Comment by Anaphory** [comment]
I just cloned the `speciesnetwork` repository, and that assertion fails even in the JUnit tests in snetworktests. I guess something is broken in the implementation?

**Comment by Anaphory** [comment]
It looks to me (who still doesn't know anything about what's going on in the package) like the issue might have to do with the construction of Embeddings. When a new `Embedding` is created for a `GeneTreeInSpeciesNetwork`, that `Embedding` does not seem to be initialized unless the gene tree is loaded from XML. In that case, the `setDirection` method is called.

Other than that, `setDirection` is only called by a test helper, some simulation code, and one deep if-branch inside the `RebuildEmbedding` operator's `recurseRebuild` method, so I assume Embedding initialization is missing.

**Comment by zhangchicool** [comment]
> I just cloned the `speciesnetwork` repository, and that assertion fails even in the JUnit tests in snetworktests. I guess something is broken in the implementation?

AllTests passed for me.
<img width="245" alt="Screen Shot 2019-03-19 at 8 15 57 AM" src="https://user-images.githubusercontent.com/3209765/54571803-53177a80-4a1f-11e9-9c48-8a399f5a8972.png">
The test_3s.xml also runs fine for me.

I guess you are using a modified xml which has some faulty elements inside.  Usually it is error-prone to build one by hand. On the other hand, the package is not mature currently and it is likely to miss some specific functionality. 

It is reasonable to build the embedding when both the gene tree and species network are available. Without the gene tree, there is no embedding exist. I guess this is reason you get this error.

**Comment by Anaphory** [comment]
Hm, weird. Now I see the tests succed as well, but it appears the only changes I reverted were some tries related to #5 which were half-baked enough that they prevented compilation anyway…

Sorry to fill in this confusing issue.

Can you explain `Embedding`'s initialization and `getDirection` to me so I can dig deeper and find out what is going on?

**Comment by zhangchicool** [comment]
I'm sorry for the lack of response. A lot of things have been going on, and some related code has been lost. Closing this issue anyway...
